name: pulsedin_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
    
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  rxdart: ^0.27.3
  focus_detector: ^2.0.1
  flutter_riverpod: ^1.0.3
  responsive_builder: ^0.4.2
  fluttertoast: ^8.0.9
  event_bus: ^2.0.0
  beamer: ^1.4.0+1
  google_fonts: ^2.3.1
  package_info_plus: ^1.4.0
  proste_bezier_curve: ^2.0.2
  rflutter_alert: ^2.0.4
  cached_network_image: ^3.2.0
  loading_animation_widget: ^1.1.0+3
  flutter_svg: ^1.0.3
  custom_pop_up_menu: ^1.2.3+1
  
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 
  #  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true